name: Build Vite Site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Commit dist
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add dist
          git commit -m "Auto build dist" || echo "No changes"
          git push
