name: Build Vite Site (Bun)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Build
        run: bun run build

      - name: Commit dist
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add dist
          git commit -m "Auto build dist" || echo "No changes"
          git push
