name: Build Vite and Deploy Dist

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Commit dist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -f dist
          git commit -m "Auto build dist" || echo "No changes"
          git push
