name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar codigo de GitHub
        uses: actions/checkout@v3

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 3. Instalar dependencias y Compilar (Build)
        run: |
          npm install
          npm run build

      - name: 4. Subir archivos a Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # Cambiamos a ./ porque tu usuario ya entra directo a public_html
          server-dir: ./
          port: 21
          protocol: ftp
