name: Build and Deploy to Hostinger (SFTP)

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Vite
        run: npm run build

      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          source: "dist/*"
          target: "/home/${{ secrets.FTP_USERNAME }}/public_html/turadio/"
