name: Deploy a Hostinger

on:
  push:
    branches:
      - main  # Asegurate de que tu rama en GitHub se llame main, si es master cambialo acá

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias y Compilar
        run: |
          npm install
          npm run build

      - name: Subir a Hostinger vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./public_html/
          dangerously-disable-tls: true
